version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.6.1
    restart: always  
    hostname: es1
    container_name: es-single
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - '9200:9200'     #java、集群通信端口
      - '9300:9300'     #http通信端口
    privileged: true    #环境变量
  head:
    image: mobz/elasticsearch-head:5
    restart: always  
    hostname: head
    container_name: head
    ports:
      - '9100:9100'
  kibana:
    image: kibana:7.6.1
    restart: always  
    hostname: kibana
    container_name: kibana
    ports:
      - '5601:5601'
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    # links:
    #   - elasticsearch
networks:
  default:
      external:
          name: local
